{{- if .Values.datagen.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f /home/avigershon/projects/ksql/docs/quickstart/docker-compose.yml
      convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: ksql-datagen-pageviews
  name: ksql-datagen-pageviews
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: ksql-datagen-pageviews
status:
  loadBalancer: {}
{{- end -}}
